var _menu="	<tr>"
+"		<td height='22' align='center' background='../imgs/bg_nav_left01.gif'><a href='eq.html' class='menu1' style='color: #992e00'>儿童情商指导师培训课程</a></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='1'></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='22' align='center' background='../imgs/bg_nav_left01.gif'><a href='eqteacher.html' class='menu1' style='color: #992e00'>情商指导师师资</a></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='1'></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='22' align='center' background='../imgs/bg_nav_left01.gif'><a href='eqabout.html' class='menu1' style='color: #992e00'>什么是情商教育?</a></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='1'></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='22' align='center' background='../imgs/bg_nav_left01.gif'><a href='howto.html' class='menu1' style='color: #992e00'>如何培养孩子的情商?</a></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='1'></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='22' align='center' background='../imgs/bg_nav_left01.gif'><a href='12.html' class='menu1' style='color: #992e00'>教育孩子12法则</a></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='1'></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='22' align='center' background='../imgs/bg_nav_left01.gif'><a href='kc.html' class='menu1' style='color: #992e00'>情商沙盘</a></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='1'></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='22' align='center' background='../imgs/bg_nav_left01.gif'><a href='kc1.html' class='menu1' style='color: #992e00'>专注力训练课程</a></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='1'></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='45' align='center'>&nbsp;</td>"
+"	</tr>"
+"	<tr>"
+"		<td align='center'><a href='javascript:void(0);' onclick='return false;'><img src='../imgs/banner_150_1.jpg' width='150' height='50' border='0'></a></td>"
+"	</tr>"
+"	<tr>"
+"		<td align='center'>&nbsp;</td>"
+"	</tr>"
+"	<tr>"
+"		<td align='center'><a href='../koucai/bm.html'><img src='../imgs/banner_150_2.jpg' width='150' height='50' border='0'></a></td>"
+"	</tr>"
+"	<tr>"
+"		<td align='center'>&nbsp;</td>"
+"	</tr>"
+"	<tr>"
+"		<td align='center'><a href='../koucai/online.html'><img src='../imgs/banner_150_4.jpg' width='150' height='50' border='0'></a></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='30' align='center'>&nbsp;</td>"
+"	</tr>";
$(document).ready(function(){
	$("#_menu").html(_menu);
});