var _menu="	<tr>"
+"		<td height='22' align='center' background='../imgs/bg_nav_left01.gif'><a href='eq.html' class='menu1' style='color: #992e00'>关于亲子营</a></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='1'></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='22' align='center' background='../imgs/bg_nav_left01.gif'><a href='acti.html' class='menu1' style='color: #992e00'>亲子营活动介绍</a></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='1'></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='22' align='center' background='../imgs/bg_nav_left01.gif'><a href='actiFeat.html' class='menu1' style='color: #992e00'>亲子营活动特色</a></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='1'></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='22' align='center' background='../imgs/bg_nav_left01.gif'><a href='wonderful.html' class='menu1' style='color: #992e00'>精彩回顾</a></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='1'></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='22' align='center' background='../imgs/bg_nav_left01.gif'><a href='bm.html' class='menu1' style='color: #992e00'>在线报名</a></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='1'></td>"
+"	</tr>";

var _acti="	<tr>"
	+"		<td height='22' align='center' background='../imgs/bg_nav_left01.gif'><a href='bjSummerCamp.html' class='menu1' style='color: #992e00'>我来北京过暑假</a></td>"
	+"	</tr>"
	+"	<tr>"
	+"		<td height='1'></td>"
	+"	</tr>"
	+"	</tr>"
	+ "	<tr>"
	+"		<td height='22' align='center' background='../imgs/bg_nav_left01.gif'><a href='happyWeekend.html' class='menu1' style='color: #992e00'>2013年5月11日亲子营训活动</a></td>"
	+"	</tr>"
	+"	<tr>"
	+"		<td height='1'></td>"
	+"	</tr>"
	+"	<tr>"
	+"		<td height='45' align='center'>&nbsp;</td>"
	+"	</tr>"
	+"	<tr>"
	+"		<td align='center'><a href='javascript:void(0);' onclick='return false;'><img src='../imgs/banner_150_1.jpg' width='150' height='50' border='0'></a></td>"
	+"	</tr>"
	+"	<tr>"
	+"		<td align='center'>&nbsp;</td>"
	+"	</tr>"
	+"	<tr>"
	+"		<td align='center'><a href='../koucai/bm.html'><img src='../imgs/banner_150_2.jpg' width='150' height='50' border='0'></a></td>"
	+"	</tr>"
	+"	<tr>"
	+"		<td align='center'>&nbsp;</td>"
	+"	</tr>"
	+"	<tr>"
	+"		<td align='center'><a href='../koucai/online.html'><img src='../imgs/banner_150_4.jpg' width='150' height='50' border='0'></a></td>"
	+"	</tr>"
	+"	<tr>"
	+"		<td height='30' align='center'>&nbsp;</td>"
	+"	</tr>";
$(document).ready(function(){
	$("#_menu").html(_menu);
	$("#_acti").html(_acti);
});