var _menu="	<tr>"
+"		<td height='22' align='center' background='../imgs/bg_nav_left01.gif'><a href='list.html' class='menu1' style='color: #992e00'>风采展示</a></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='22' align='center' background='../imgs/bg_nav_left01.gif'><a href='contact.html' class='menu1' style='color: #992e00'>联系我们</a></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='1'></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='22' align='center' background='../imgs/bg_nav_left01.gif'><a href='hr.html' class='menu1' style='color: #992e00'>诚聘英才</a></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='1'></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='45' align='center'>&nbsp;</td>"
+"	</tr>"
+"	<tr>"
+"		<td align='center'><a href='javascript:void(0);' onclick='return false;'><img src='../imgs/banner_150_1.jpg' width='150' height='50' border='0'></a></td>"
+"	</tr>"
+"	<tr>"
+"		<td align='center'>&nbsp;</td>"
+"	</tr>"
+"	<tr>"
+"		<td align='center'><a href='../koucai/bm.html'><img src='../imgs/banner_150_2.jpg' width='150' height='50' border='0'></a></td>"
+"	</tr>"
+"	<tr>"
+"		<td align='center'>&nbsp;</td>"
+"	</tr>"
+"	<tr>"
+"		<td align='center'><a href='../koucai/online.html'><img src='../imgs/banner_150_4.jpg' width='150' height='50' border='0'></a></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='30' align='center'>&nbsp;</td>"
+"	</tr>";
$(document).ready(function(){
	$("#_menu").html(_menu);
});