var _menu="	<tr>"
+"		<td height='22' align='center' background='../imgs/bg_nav_left01.gif'><a href='classes.html' class='menu1' style='color: #992e00'>口才与情商课程体系</a></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='1'></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='22' align='center' background='../imgs/bg_nav_left01.gif'><a href='yanchu.html' class='menu1' style='color: #992e00'>口才与情商汇报演出</a></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='1'></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='22' align='center' background='../imgs/bg_nav_left01.gif'><a href='koucai.html' class='menu1' style='color: #992e00'>口才与情商教学九大特色</a></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='1'></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='22' align='center' background='../imgs/bg_nav_left01.gif'><a href='teacher.html' class='menu1' style='color: #992e00'>儿童口才专业师资</a></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='1'></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='22' align='center' background='../imgs/bg_nav_left01.gif'><a href='eqabout.html' class='menu1' style='color: #992e00'>什么是情商教育？</a></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='1'></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='22' align='center' background='../imgs/bg_nav_left01.gif'><a href='online.html' class='menu1' style='color: #992e00'>在线咨询</a></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='1'></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='22' align='center' background='../imgs/bg_nav_left01.gif'><a href='bm.html' class='menu1' style='color: #992e00'>在线报名</a></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='1'></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='45' align='center'>&nbsp;</td>"
+"	</tr>"
+"	<tr>"
+"		<td align='center'><a href='javascript:void(0);' onclick='return false;'><img src='../imgs/banner_150_1.jpg' width='150' height='50' border='0'></a></td>"
+"	</tr>"
+"	<tr>"
+"		<td align='center'>&nbsp;</td>"
+"	</tr>"
+"	<tr>"
+"		<td align='center'><a href='../koucai/bm.html'><img src='../imgs/banner_150_2.jpg' width='150' height='50' border='0'></a></td>"
+"	</tr>"
+"	<tr>"
+"		<td align='center'>&nbsp;</td>"
+"	</tr>"
+"	<tr>"
+"		<td align='center'><a href='../koucai/online.html'><img src='../imgs/banner_150_4.jpg' width='150' height='50' border='0'></a></td>"
+"	</tr>"
+"	<tr>"
+"		<td height='30' align='center'>&nbsp;</td>"
+"	</tr>";
$(document).ready(function(){
	$("#_menu").html(_menu);
});